CREATE TABLE CANTEEN
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ProviderID INTEGER,
    Name TEXT,
    Location TEXT,
    time_open TIME,
    time_closed TIME,
    FOREIGN KEY(ProviderID) REFERENCES PROVIDER(ID)
);